### ISSUE TITLE
Build log system

### ISSUE THREAD

**Issue by ghermans** [idevelopment/serviceforce#71]
Log all changes for servers.

![logs](https://cloud.githubusercontent.com/assets/1594411/17645160/55978dda-619d-11e6-9174-014f9a6dc93a.PNG)
## Todo
- [ ] Create a new migration file.
- [ ] Create ServerLog model.
- [ ] Create seeder.
- [ ] Add log method to the provisioning task.

**Comment by Tjoosten** [comment]
Is there a api url for this data? @ghermans

**Comment by ghermans** [comment]
no this is just a static table.

**Comment by ghermans** [comment]
## Todo

- [ ] Create a new migration file.
- [ ] Create ServerLog model.
- [ ] Create seeder.
